CREATE TABLE roles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO roles (name) VALUES 
('ADMIN'),
('OPERADOR'),
('USER')
ON CONFLICT (name) DO NOTHING;